/*
SIGHTAI-SERVICES

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WithdrawRequest struct for WithdrawRequest
type WithdrawRequest struct {
	Amount string `json:"amount"`
}

// NewWithdrawRequest instantiates a new WithdrawRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithdrawRequest(amount string) *WithdrawRequest {
	this := WithdrawRequest{}
	this.Amount = amount
	return &this
}

// NewWithdrawRequestWithDefaults instantiates a new WithdrawRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithdrawRequestWithDefaults() *WithdrawRequest {
	this := WithdrawRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *WithdrawRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *WithdrawRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *WithdrawRequest) SetAmount(v string) {
	o.Amount = v
}

func (o WithdrawRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableWithdrawRequest struct {
	value *WithdrawRequest
	isSet bool
}

func (v NullableWithdrawRequest) Get() *WithdrawRequest {
	return v.value
}

func (v *NullableWithdrawRequest) Set(val *WithdrawRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWithdrawRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWithdrawRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithdrawRequest(val *WithdrawRequest) *NullableWithdrawRequest {
	return &NullableWithdrawRequest{value: val, isSet: true}
}

func (v NullableWithdrawRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithdrawRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


