/*
SIGHTAI-SERVICES

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DepositRequest ONLY FOR ADMIN TEST
type DepositRequest struct {
	Address string `json:"address"`
	Amount string `json:"amount"`
}

// NewDepositRequest instantiates a new DepositRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepositRequest(address string, amount string) *DepositRequest {
	this := DepositRequest{}
	this.Address = address
	this.Amount = amount
	return &this
}

// NewDepositRequestWithDefaults instantiates a new DepositRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepositRequestWithDefaults() *DepositRequest {
	this := DepositRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *DepositRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *DepositRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *DepositRequest) SetAddress(v string) {
	o.Address = v
}

// GetAmount returns the Amount field value
func (o *DepositRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *DepositRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *DepositRequest) SetAmount(v string) {
	o.Amount = v
}

func (o DepositRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["address"] = o.Address
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableDepositRequest struct {
	value *DepositRequest
	isSet bool
}

func (v NullableDepositRequest) Get() *DepositRequest {
	return v.value
}

func (v *NullableDepositRequest) Set(val *DepositRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDepositRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDepositRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepositRequest(val *DepositRequest) *NullableDepositRequest {
	return &NullableDepositRequest{value: val, isSet: true}
}

func (v NullableDepositRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepositRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


