/*
SIGHTAI-SERVICES

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionsResponse struct for TransactionsResponse
type TransactionsResponse struct {
	Transactions []Transaction `json:"transactions,omitempty"`
}

// NewTransactionsResponse instantiates a new TransactionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionsResponse() *TransactionsResponse {
	this := TransactionsResponse{}
	return &this
}

// NewTransactionsResponseWithDefaults instantiates a new TransactionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionsResponseWithDefaults() *TransactionsResponse {
	this := TransactionsResponse{}
	return &this
}

// GetTransactions returns the Transactions field value if set, zero value otherwise.
func (o *TransactionsResponse) GetTransactions() []Transaction {
	if o == nil || o.Transactions == nil {
		var ret []Transaction
		return ret
	}
	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionsResponse) GetTransactionsOk() ([]Transaction, bool) {
	if o == nil || o.Transactions == nil {
		return nil, false
	}
	return o.Transactions, true
}

// HasTransactions returns a boolean if a field has been set.
func (o *TransactionsResponse) HasTransactions() bool {
	if o != nil && o.Transactions != nil {
		return true
	}

	return false
}

// SetTransactions gets a reference to the given []Transaction and assigns it to the Transactions field.
func (o *TransactionsResponse) SetTransactions(v []Transaction) {
	o.Transactions = v
}

func (o TransactionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Transactions != nil {
		toSerialize["transactions"] = o.Transactions
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionsResponse struct {
	value *TransactionsResponse
	isSet bool
}

func (v NullableTransactionsResponse) Get() *TransactionsResponse {
	return v.value
}

func (v *NullableTransactionsResponse) Set(val *TransactionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionsResponse(val *TransactionsResponse) *NullableTransactionsResponse {
	return &NullableTransactionsResponse{value: val, isSet: true}
}

func (v NullableTransactionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


