/*
SIGHTAI-SERVICES

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SignInRequest struct for SignInRequest
type SignInRequest struct {
	Address string `json:"address"`
	Domain *string `json:"domain,omitempty"`
}

// NewSignInRequest instantiates a new SignInRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignInRequest(address string) *SignInRequest {
	this := SignInRequest{}
	this.Address = address
	return &this
}

// NewSignInRequestWithDefaults instantiates a new SignInRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignInRequestWithDefaults() *SignInRequest {
	this := SignInRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *SignInRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *SignInRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *SignInRequest) SetAddress(v string) {
	o.Address = v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *SignInRequest) GetDomain() string {
	if o == nil || o.Domain == nil {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInRequest) GetDomainOk() (*string, bool) {
	if o == nil || o.Domain == nil {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *SignInRequest) HasDomain() bool {
	if o != nil && o.Domain != nil {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *SignInRequest) SetDomain(v string) {
	o.Domain = &v
}

func (o SignInRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["address"] = o.Address
	}
	if o.Domain != nil {
		toSerialize["domain"] = o.Domain
	}
	return json.Marshal(toSerialize)
}

type NullableSignInRequest struct {
	value *SignInRequest
	isSet bool
}

func (v NullableSignInRequest) Get() *SignInRequest {
	return v.value
}

func (v *NullableSignInRequest) Set(val *SignInRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignInRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignInRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignInRequest(val *SignInRequest) *NullableSignInRequest {
	return &NullableSignInRequest{value: val, isSet: true}
}

func (v NullableSignInRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignInRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


